# Generated by Django 5.0.3 on 2024-03-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Missing image', upload_to='Images/'),
        ),
    ]
