# Generated by Django 5.0.3 on 2024-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_user_name',
            field=models.CharField(default='Anonymous post', max_length=30),
        ),
    ]
